### ISSUE TITLE
Defining .+ derivative does not work

### ISSUE THREAD

**Issue by rosstang** [LaurenceA/ReverseDiffOverload.jl#3]
I found a few issues when trying to define derivative of operator .+

julia> using ReverseDiffOverload

julia> ReverseDiffOverload.@d2(.+, d .+ zeros(size(y)), d .+ zeros(size(x)))
ERROR: Call not defined
### Here, Call is not exported

julia> import ReverseDiffOverload.Call

julia> ReverseDiffOverload.@d2(.+, d .+ zeros(size(y)), d .+ zeros(size(x)))
diff_con (generic function with 1 method)

julia> reversediff((x,y)->x .+ y, [1 2 3;4 5 6], [1,2])
ERROR: `diff_con` has no method matching diff_con(::Call{:.+,Array{Float64,2},(Call{Nothing,Array{Float64,2},()},Call{No
thing,Array{Float64,1},()})}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1})
 in diff at C:\Users\ross.julia\v0.3\ReverseDiffOverload\src\ReverseDiffOverload.jl:45
 in diff at C:\Users\ross.julia\v0.3\ReverseDiffOverload\src\ReverseDiffOverload.jl:38

Is there any way to make .+ works?

Thanks a lot.

**Comment by LaurenceA** [comment]
See recent commit --- could you open a new issue if it still isn't working?
